"""Minimal vernacular i18n. No hardcoded English in user-facing surfaces.

v1 ships English + Hindi (beachhead). Languages are added by extending STRINGS.
Closer/Reporter agent copy is generated by the LLM in-language; this table is for
deterministic system strings (errors, notifications, fixed UI labels served by the API).
"""
from __future__ import annotations

SUPPORTED_LOCALES = ("en", "hi", "ta", "te", "mr", "gu", "kn", "bn")
DEFAULT_LOCALE = "en"

STRINGS: dict[str, dict[str, str]] = {
    "error.generic": {
        "en": "Something went wrong. Please try again.",
        "hi": "कुछ गड़बड़ हो गई। कृपया फिर से कोशिश करें।",
    },
    "error.validation": {
        "en": "Please check the details you entered.",
        "hi": "कृपया दर्ज की गई जानकारी जाँच लें।",
    },
    "error.unauthorized": {
        "en": "Please sign in to continue.",
        "hi": "जारी रखने के लिए कृपया साइन इन करें।",
    },
    "error.forbidden": {
        "en": "You don't have access to this.",
        "hi": "आपके पास इसकी अनुमति नहीं है।",
    },
    "error.not_found": {
        "en": "We couldn't find what you were looking for.",
        "hi": "हमें वह नहीं मिला जो आप ढूँढ रहे थे।",
    },
    "error.conflict": {
        "en": "This was already done.",
        "hi": "यह पहले ही हो चुका है।",
    },
    "notify.hot_lead.title": {
        "en": "🔥 Hot lead",
        "hi": "🔥 ज़बरदस्त ग्राहक",
    },
    "notify.hot_lead.body": {
        "en": "{name} is interested in {intent}. Reply now on WhatsApp.",
        "hi": "{name} को {intent} में दिलचस्पी है। अभी WhatsApp पर जवाब दें।",
    },
}


def t(key: str, locale: str = DEFAULT_LOCALE, **kwargs: object) -> str:
    """Translate a key for a locale, falling back to English then the key itself."""
    table = STRINGS.get(key, {})
    template = table.get(locale) or table.get(DEFAULT_LOCALE) or key
    if kwargs:
        try:
            return template.format(**kwargs)
        except (KeyError, IndexError):
            return template
    return template


def normalize_locale(locale: str | None) -> str:
    if not locale:
        return DEFAULT_LOCALE
    short = locale.split("-")[0].lower()
    return short if short in SUPPORTED_LOCALES else DEFAULT_LOCALE
